### ISSUE TITLE
Add support for symbols

### ISSUE THREAD

**Issue by kilasuit** [mmcmd/Get-RandomPassword#19]
Symbols are often needed in passwords so this should allow support for them too

**Comment by mmcmd** [comment]
Hi Ryan, symbols are supported through the `-Delimiter` parameter, for example:

```powershell
PS> Get-Randompassword -Words 4 -Count 1 -Delimiter "@^!" -Donotcopytoclipboard
HIGHEST@^!crafts@^!SHARP@^!DEALING
```

Or were you thinking of another way?

**Comment by kilasuit** [comment]
I apolgise as I couldn't see this clearly in the diocumentation on a very quick read which is more my bad than your documentation!

**Comment by mmcmd** [comment]
No problem!
